
version: "3"
services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
 
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge